### ISSUE TITLE
Tried setting debug on Mac for InDesign but it not work

### ISSUE THREAD

**Issue by ilentt** [rendertom/VSCode-Adobe-Script-Runner#10]
I have tried setting debug on Mac(Mojave 10.14.5) but it look like does not work with me. I also did not found indesign setting. Could you please show me where I was wrong and and how to setting correct.

![](https://i.imgur.com/p39TX4Q.png)

**Comment by rendertom** [comment]
Hey Illentt. What debug are you talking about? There's no debug mode in Adobe Script Runner.
Regarding InDesign settings - what settings? What are you trying to achieve?
