### ISSUE TITLE
Run script from a command line

### ISSUE THREAD

**Issue by zadlo** [rendertom/VSCode-Adobe-Script-Runner#12]
Is there a way to run exacute script-runner from command line? I would like to run it from gulp.

**Comment by Inventsable** [comment]
Pretty sure you can do this in any terminal and perhaps through a childProcess or shell package from within gulp. Something like:

```bash
"C:\Program Files\Adobe\Adobe Illustrator CC 2018\Support Files\Contents\Windows\illustrator.exe" -r "C:\Users\TRSch\OneDrive\Documents\Adobe Scripts\examples\test.jsx"
```

**Comment by rendertom** [comment]
What @Inventsable said.

The extension works by simply executing a shell command and passing the file in the active viewer.
Feel free to open `hostApps.js` file from the extension folder `rendertom.adobe-script-runner-0.3.0/lib/hostApps.js` and see all available commands.

Cheers.
