### ISSUE TITLE
Extension not working in InDesign CC 2019 on Windows 10

### ISSUE THREAD

**Issue by leonardpin-br** [rendertom/VSCode-Adobe-Script-Runner#13]
The extension is not working in Adobe InDesign CC 2019 (14.0.3).
I keep receiving the message "Script sent to Adobe InDesign", but not happens.
It does not work with Adobe ExtendScritp Toolkit either.

**Comment by Inventsable** [comment]
What script are you trying? Script may be silently failing due to error. Are you trying something complex, or simple like:

```js 
alert(app.name)
```

**Comment by leonardpin-br** [comment]
Thank you for the fast answer.
When I commented, I was at work. There, the extension does not work in InDesign.
I have just arrived at my house. Here, the extension works. I installed both at home and at the work computer.
I was trying
`alert("Hello, World!");`
Do you have any suggestions on how I can debug it?
I already uninstalled the extension many times. I uninstalled Visual Studio Code too and reinstalled. Did not work.

**Comment by rendertom** [comment]
Could it be possible that somehow your computer is locked from running shell commands? Maybe a permission issue? The way extension works under the hood is it invokes shell command and passes the path to the file in the active viewer. So no real magic here.
