### ISSUE TITLE
Issue with Photoshop 2020 path setting on Win10

### ISSUE THREAD

**Issue by pto2k** [rendertom/VSCode-Adobe-Script-Runner#14]
It fails to send the script to Photoshop with an error saying it can not find the Photoshop file.
But I have the path put in the setting:
"adobeScriptRunner.winPhotoshopExe": "C:/Program Files/Adobe/Adobe Photoshop CC 2020/Photoshop.exe"

I'm not sure if it's some Win10 security thing?

However, I figured out a workaround: made a .lnk file pointing to the Photoshop.exe, then use the path of that .lnk file for the Runner's setting.

It works!

**Comment by rendertom** [comment]
Any chance you have a bad link?
I don't have PC so I cannot confirm, but in the latest CC version (2020) the Adobe ditched **CC** from the name. So path, at least on a mac, looks like this: `/Applications/Adobe Photoshop 2020/Adobe Photoshop 2020.app`

**Comment by natyconnor** [comment]
Yeah, that's exactly it. Same on PC. It should be `C:\Program Files\Adobe\Adobe Photoshop 2020\Photoshop.exe`
