### ISSUE TITLE
How to remove the warning window in PS？

### ISSUE THREAD

**Issue by MrDesignLGC** [rendertom/VSCode-Adobe-Script-Runner#15]
I've tried to add psuserconfig code, but it doesn't work.

**Comment by rendertom** [comment]
It's not clear what you are referring to. Please update your question with more information.

**Comment by MrDesignLGC** [comment]
When running the jsx code, a warning selection box will pop up in photoshop. It will run after clicking OK, and it will pop up every time, so I think there is a way to run the code directly, not to pop up the warning window?

**Comment by rendertom** [comment]
I cannot reproduce. Can you do a screen recording?

**Comment by MrDesignLGC** [comment]
That window will pop up when everyone runs, so you can try it yourself

**Comment by rendertom** [comment]
What window? Can you at least upload a screenshot?
I tested on macOS and didn't see any issues.

**Comment by MrDesignLGC** [comment]
![123](https://user-images.githubusercontent.com/55623874/79048322-f2bd3180-7c4e-11ea-9f1b-e060c2052640.png)
This is the window. I don't want it to pop up

**Comment by natyconnor** [comment]
English screenshot
![image](https://user-images.githubusercontent.com/831626/79185381-94698d80-7dcb-11ea-8245-6e3645423b1a.png)
Seems pretty clear you have to add a line to `PSUserConfig.txt` I guess Photoshop is more weary of executing scripts.

**Comment by MrDesignLGC** [comment]
Add the code in "PSUserConfig.txt" and put it in the setting file. I have done this, but it does not take effect. I think it's a problem with my computer.

**Comment by MrDesignLGC** [comment]
Adding “WarnRunningScripts 0” to “PSUserConfig.txt” did work. The reason why I failed earlier was that I installed multiple ps versions, so I put it in the wrong directory.
