### ISSUE TITLE
key binding fail

### ISSUE THREAD

**Issue by msjzs** [rendertom/VSCode-Adobe-Script-Runner#16]
hi,
on pc, I Modified keybingdings.json，"command": "adobeScriptRunner.psd".
I try this, F1 -> adobe photoshop, run photoshop success.
but, ctrl + r, it still run after effect.

**Comment by rendertom** [comment]
Can you post your keybinding.json file content?
I tried this on mac, and it works as expected - Ctrl+R launches script inside Photoshop:
```
{
    "key": "cmd+r",
    "command": "adobeScriptRunner.psd",
    "when": "editorTextFocus"
},
```

**Comment by msjzs** [comment]
yeap,same as you.
the full contents of the keybindings.json file are as follows:

[
    {
        "key": "cmd+r",
        "command": "adobeScriptRunner.psd",
        "when": "editorTextFocus"
    }
]

**Comment by rendertom** [comment]
I see @msjzs closed the ticket.
Were you able to find a solution? If so, what was it?
