### ISSUE TITLE
Run beta versions on Mac

### ISSUE THREAD

**Issue by mrspartak** [rendertom/VSCode-Adobe-Script-Runner#20]
My use-case is that I'm using the beta version of After Effects on Mac. But the code runs in a normal version. Is there a way to set up a program path for Mac?

**Comment by rendertom** [comment]
Hey there.
This sounds as a good PR.
Meanwhile, you can manually modify the `hostApps` file to target beta version of the app. I know it's not perfect, but it is what it is.

Find the `hostApps` file here: `/Users/YOUR USER NAME/.vscode/extensions/rendertom.adobe-script-runner-0.5.0/lib/hostApps.js` and then modify the 5'th line of code: <...>"com.adobe.**aftereffects**"<...> into <...>"com.adobe.**aftereffectsBeta**" <...>. This should do the trick for now.

**Comment by rendertom** [comment]
I'll have this implemented in the next release

**Comment by rendertom** [comment]
Implemented in https://github.com/rendertom/VSCode-Adobe-Script-Runner/commit/4def7e6233f27e0c4212f168ab48c647a7a00b89
