### ISSUE TITLE
After Effects CC 2014 Full Screen Gets Resized Upon Running Script When Snapped

### ISSUE THREAD

**Issue by JohnTravolski** [rendertom/VSCode-Adobe-Script-Runner#4]
On Windows 10, whenever I use ExtendScript ToolKit to run my script, the After Effects window does not get focus and remains exactly in its current location.  This is preferable.

However, when I use this tool, the Window always gets resized for some reason, but only if the AE window is snapped.  Here's a screenshot with before running and after running using this tool in VS Code:

BEFORE:
https://i.imgur.com/81NhqLA.png

AFTER:
https://i.imgur.com/ylp3Pkb.png

Notice how the window resized itself.  If my AE window is either full screen (maximized) size or snapped to the left or right, this happens.  It does not happen otherwise.  Is there any way to prevent it from resizing itself when the window is maximized?

**Comment by Andrei1911** [comment]
This happens to any tool that tries to run scripts other than ESTK. Even when ran from the command line, this still happens to me. I just make the window close to max so it does not bother me.

**Comment by rendertom** [comment]
As @Andrei1911 said.
Extension by itself doesn't change/modify the host application size/location. This must be the Os thing.
