### ISSUE TITLE
Silent execution

### ISSUE THREAD

**Issue by japettyjohn** [rendertom/VSCode-Adobe-Script-Runner#8]
For a smoother development flow I think, optionally if nothing else, that the command for the apps does not activate the window.

This can be achieved on macOS by removing 'activate' from the darwin commands.

I've started this on my [fork](https://github.com/japettyjohn/VSCode-Adobe-Script-Runner/commit/7b2456720e4b7b26817538c4f85c03edd2777448). 

What I was not able to do so far was get the output from the script into the console. If you execute the command manually from the command line, without activating the target window, the last value in the script will be output in the console. This will also be better aligned with InDesign Server automation which works the same way with it's SOAP calls.

This is far better than alert boxes.

**Comment by rendertom** [comment]
Hey @japettyjohn. Thanks for the suggestion. I've implemented an option to run in silent mode.
But I am not sure how to go about printing the output to the console.
