### ISSUE TITLE
Add support for Premiere Pro

### ISSUE THREAD

**Issue by KevinKelbie** [rendertom/VSCode-Adobe-Script-Runner#9]
Great extension! Would it be possible for you to add support for Premiere Pro (especially for mac)?

**Comment by n9cht** [comment]
+1

**Comment by rendertom** [comment]
I would love to support all Adobe applications, however, Premiere does not work with shell commands, which is the core principle of this extension.

If I find a way in the future, I'll definitely implement it.

**Comment by MotorCityCobra** [comment]
I came to this extension because Extend Script doesn't do execute scripts on Premiere Pro.  
So... Does anything run scripts for Premiere Pro?
